export default{
    "kind": "customsearch#search",
    "url": {
        "type": "application/json",
        "template": "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json"
    },
    "queries": {
        "request": [
            {
                "title": "Google Custom Search - {context.query.term}",
                "totalResults": "206000",
                "searchTerms": "{context.query.term}",
                "count": 10,
                "startIndex": 1,
                "inputEncoding": "utf8",
                "outputEncoding": "utf8",
                "safe": "off",
                "cx": "136f7998e535c4dc1"
            }
        ],
        "nextPage": [
            {
                "title": "Google Custom Search - {context.query.term}",
                "totalResults": "206000",
                "searchTerms": "{context.query.term}",
                "count": 10,
                "startIndex": 11,
                "inputEncoding": "utf8",
                "outputEncoding": "utf8",
                "safe": "off",
                "cx": "136f7998e535c4dc1"
            }
        ]
    },
    "context": {
        "title": "google"
    },
    "searchInformation": {
        "searchTime": 0.408961,
        "formattedSearchTime": "0.41",
        "totalResults": "206000",
        "formattedTotalResults": "206,000"
    },
    "items": [
        {
            "kind": "customsearch#result",
            "title": "7.4 - Search Appliance Internationalization",
            "htmlTitle": "7.4 - Search Appliance Internationalization",
            "link": "https://www.google.com/support/enterprise/static/gsa/docs/admin/current/gsa_doc_set/internationalization/internationalization.html",
            "displayLink": "www.google.com",
            "snippet": "In some cases, the query might need additional context. For example, a single-word search term might not trigger query expansion, but adding additional search ...",
            "htmlSnippet": "In some cases, the <b>query</b> might need additional <b>context</b>. For example, a single-<b>word</b> search <b>term</b> might not trigger <b>query</b> expansion, but adding additional search&nbsp;...",
            "cacheId": "P13-IOmoHT8J",
            "formattedUrl": "https://www.google.com/support/enterprise/.../internationalization.html",
            "htmlFormattedUrl": "https://www.google.com/support/enterprise/.../internationalization.html"
        },
        {
            "kind": "customsearch#result",
            "title": "US7974964B2 - Context based search and document retrieval ...",
            "htmlTitle": "US7974964B2 - <b>Context</b> based search and document retrieval ...",
            "link": "https://www.google.com/patents/US7974964",
            "displayLink": "www.google.com",
            "snippet": "The context data is provided to a search query generator. ... The bookmarked documents are hyperlinked to terms in the browsed document.",
            "htmlSnippet": "The <b>context</b> data is provided to a search <b>query</b> generator. ... The bookmarked documents are hyperlinked to <b>terms</b> in the browsed document.",
            "formattedUrl": "https://www.google.com/patents/US7974964",
            "htmlFormattedUrl": "https://www.google.com/patents/US7974964",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRU-OzlMrzrM7xOBXIKfHj7rFKMLEWpZN9aI0rARYYfrx6DqupF2lWFtw",
                        "width": "108",
                        "height": "120"
                    }
                ],
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:11/654,324",
                        "citation_patent_number": "US:7974964",
                        "dc.description": "A context based search and document retrieval application is disclosed. The application uses context data that is generated by a document analysis component based upon context information from various sources, including for example, document collections available on the world wide web. The context data is provided to a search query generator. The search query generator is configured to generate a contextually annotated search query based upon a user query and context data. Bookmarks having an associated context are generated for documents retrieved in response to the contextually annotated search query. The application then provides access to the bookmarked documents when the user is browsing other documents with similar contexts to the context of the original document for which the context based search was executed and the bookmark created. The bookmarked documents are hyperlinked to terms in the browsed document.",
                        "dc.type": "patent",
                        "citation_reference": "\"A Web-Based Process and Process Models to Find and Deliver Information to Improve the Quality of Flight Software\", J. Scott Hawker et al., University of Alabama, Tuscaloosa, Alabama, 11 pages, 2003, http://cs.ua.edu/SEL/Publications/Standards-Advisor/Web-Based-Process-and-Process-models-DASC-2003 pdf.",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:6240412",
                        "dc.title": "Context based search and document retrieval",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/13/96/9f/72f1ae25b81883/US7974964.pdf",
                        "dc.date": "2007-01-17",
                        "dc.contributor": "Silviu P. Cucerzan"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://patentimages.storage.googleapis.com/15/2d/1e/730802287116ff/US07974964-20110705-D00005.png"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "EP1782380A4 - Search systems and methods using in-line ...",
            "htmlTitle": "EP1782380A4 - Search systems and methods using in-line ...",
            "link": "https://www.google.com/patents/EP1782380A4",
            "displayLink": "www.google.com",
            "snippet": "When the user submits a search query via the contextual search interface, ... to a page in which that term appears and a context identifier for the page.",
            "htmlSnippet": "When the user submits a search <b>query</b> via the <b>contextual</b> search interface, ... to a page in which that <b>term</b> appears and a <b>context</b> identifier for the page.",
            "formattedUrl": "https://www.google.com/patents/EP1782380A4",
            "htmlFormattedUrl": "https://www.google.com/patents/EP1782380A4",
            "pagemap": {
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "EP:05774749A",
                        "dc.description": "Systems and methods are provided for implementing searches using contextual information associated with a Web page (or other document) that a user is viewing when a query is entered. The page includes a contextual search interface that has an associated context vector representing content of the page. When the user submits a search query via the contextual search interface, the query and the context vector are both provided to the query processor and used in responding to the query.",
                        "citation_patent_publication_number": "EP:1782380:A4",
                        "dc.type": "patent",
                        "citation_reference": "SUGIYAMA KAZUNARI ET AL: \"Adaptive Web search based on user profile constructed without any effort from users\", INTERNATIONAL WORLD WIDE WEB CONFERENCE, XX, XX, 17 May 2004 (2004-05-17), pages 675 - 684, XP002434325",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:5619709",
                        "dc.title": "Search systems and methods using in-line contextual queries",
                        "dc.date": "2005-07-21",
                        "dc.contributor": "Reiner Kraft"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "US20100106719A1 - Context-sensitive search - Google Patents",
            "htmlTitle": "US20100106719A1 - <b>Context</b>-sensitive search - Google Patents",
            "link": "http://www.google.com/patents/US20100106719",
            "displayLink": "www.google.com",
            "snippet": "The method involves receiving a search request comprising a query term and a context document, and identifying a target document of a plurality of documents ...",
            "htmlSnippet": "The method involves receiving a search request comprising a <b>query term</b> and a <b>context</b> document, and identifying a target document of a plurality of documents&nbsp;...",
            "formattedUrl": "www.google.com/patents/US20100106719",
            "htmlFormattedUrl": "www.google.com/patents/US20100106719",
            "pagemap": {
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:12/257,211",
                        "dc.description": "A method for performing a search based on a query term and a context document is described herein. The method involves receiving a search request comprising a query term and a context document, and identifying a target document of a plurality of documents based on a relationship of the context document with the target document and the query term, where the relationship of the context document with the target document is determined prior to receiving the search request.",
                        "citation_patent_publication_number": "US:20100106719:A1",
                        "dc.type": "patent",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:5265065",
                        "dc.title": "Context-sensitive search",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/a9/71/87/818b9ccc525173/US20100106719A1.pdf",
                        "dc.date": "2008-10-23",
                        "dc.contributor": "Debora Donato"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "Ranking Results – How Google Search Works",
            "htmlTitle": "Ranking Results – How Google Search Works",
            "link": "https://www.google.com/search/howsearchworks/how-search-works/ranking-results/",
            "displayLink": "www.google.com",
            "snippet": "Meaning; Relevance; Quality; Usability; Context. Meaning of your query. To return relevant results, ...",
            "htmlSnippet": "Meaning; Relevance; Quality; Usability; <b>Context</b>. Meaning of your <b>query</b>. To return relevant results,&nbsp;...",
            "cacheId": "V3QUFekmi_gJ",
            "formattedUrl": "https://www.google.com/search/howsearchworks/how.../ranking-results/",
            "htmlFormattedUrl": "https://www.google.com/search/howsearchworks/how.../ranking-results/",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGS3cygt5kGAiZY-7hO8fSAHJHy5cC3mlOzc5Dbg3h6qghrry_RtnEAEo",
                        "width": "310",
                        "height": "163"
                    }
                ],
                "metatags": [
                    {
                        "og:image": "https://lh3.googleusercontent.com/dnpoiu9aopdadx61b_R8SlKyCHQIBNSTlYKOqUdZ1J8RPl3dGu1i57tmb7KzVEgpjdD_wc-CFirNtxU3wDiS9b1ZNAYxqq4tyojt5X4Q",
                        "og:type": "website",
                        "twitter:card": "summary",
                        "twitter:title": "Ranking Results – How Google Search Works",
                        "og:site_name": "Google Search - Discover How Google Search Works",
                        "og:title": "Ranking Results – How Google Search Works",
                        "og:description": "With the vast amount of information available, finding what you need would be nearly impossible without some help sorting through it. Google’s ranking systems are designed to do just that: sort through hundreds of billions of webpages and other content in our Search index to present the most relevant, useful results in a fraction of a second.",
                        "og:image:secure_url": "https://lh3.googleusercontent.com/dnpoiu9aopdadx61b_R8SlKyCHQIBNSTlYKOqUdZ1J8RPl3dGu1i57tmb7KzVEgpjdD_wc-CFirNtxU3wDiS9b1ZNAYxqq4tyojt5X4Q",
                        "twitter:image": "https://lh3.googleusercontent.com/dnpoiu9aopdadx61b_R8SlKyCHQIBNSTlYKOqUdZ1J8RPl3dGu1i57tmb7KzVEgpjdD_wc-CFirNtxU3wDiS9b1ZNAYxqq4tyojt5X4Q",
                        "referrer": "no-referrer",
                        "viewport": "width=device-width, initial-scale=1.0",
                        "twitter:description": "With the vast amount of information available, finding what you need would be nearly impossible without some help sorting through it. Google’s ranking systems are designed to do just that: sort through hundreds of billions of webpages and other content in our Search index to present the most relevant, useful results in a fraction of a second.",
                        "og:locale": "en",
                        "og:url": "https://www.google.com/search/howsearchworks/how-search-works/ranking-results/"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://lh3.googleusercontent.com/dnpoiu9aopdadx61b_R8SlKyCHQIBNSTlYKOqUdZ1J8RPl3dGu1i57tmb7KzVEgpjdD_wc-CFirNtxU3wDiS9b1ZNAYxqq4tyojt5X4Q"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "Lesson Plan Map – Search Education – Google",
            "htmlTitle": "Lesson Plan Map – Search Education – Google",
            "link": "https://www.google.com/insidesearch/searcheducation/lesson-map.html",
            "displayLink": "www.google.com",
            "snippet": "Lesson Plan Map. Lesson 1: How can appropriate search terms and queries guide targeted searches? ... Create query; Determine appropriate context terms ...",
            "htmlSnippet": "Lesson Plan Map. Lesson 1: How can appropriate search <b>terms</b> and <b>queries</b> guide targeted searches? ... Create <b>query</b>; Determine appropriate <b>context terms</b>&nbsp;...",
            "cacheId": "5Zuei_6fZY8J",
            "formattedUrl": "https://www.google.com/insidesearch/searcheducation/lesson-map.html",
            "htmlFormattedUrl": "https://www.google.com/insidesearch/searcheducation/lesson-map.html",
            "pagemap": {
                "metatags": [
                    {
                        "viewport": "initial-scale=1, minimum-scale=1, width=device-width"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "US20040117366A1 - Method and system for interpreting multiple ...",
            "htmlTitle": "US20040117366A1 - Method and system for interpreting multiple ...",
            "link": "http://www.google.com/patents/US20040117366",
            "displayLink": "www.google.com",
            "snippet": "A query interpretation method and system uses a combination of context-independent and contextual evaluation to compute interpretations for multiple-term ...",
            "htmlSnippet": "A <b>query</b> interpretation method and system uses a combination of <b>context</b>-independent and <b>contextual</b> evaluation to compute interpretations for multiple-<b>term</b>&nbsp;...",
            "formattedUrl": "www.google.com/patents/US20040117366",
            "htmlFormattedUrl": "www.google.com/patents/US20040117366",
            "pagemap": {
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:10/317,337",
                        "dc.description": "A query interpretation method and system uses a combination of context-independent and contextual evaluation to compute interpretations for multiple-term queries. The present invention can be used to search a collection of items, each of which is associated with one or more terms. In certain embodiments, query interpretation involves generating several candidate multiple-term interpretations and scoring them to select one or more interpretations. In certain embodiments, query interpretation involves identifying single-term interpretations for the terms in the query, determining context-independent scores for those single-term interpretations, identifying a plurality of candidate multiple-term interpretations, determining a contextual score for each candidate multiple-term interpretation, and generating one or more multiple-term interpretations that are optimal with respect to a combination of the context-independent and contextual scoring functions.",
                        "citation_patent_publication_number": "US:20040117366:A1",
                        "dc.type": "patent",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:4996642",
                        "dc.title": "Method and system for interpreting multiple-term queries",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/9c/a9/f6/c42c795bf0aebb/US20040117366A1.pdf",
                        "dc.date": "2002-12-12",
                        "dc.contributor": "Adam Ferrari"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "US9141672B1 - Click or skip evaluation of query term ...",
            "htmlTitle": "US9141672B1 - Click or skip evaluation of <b>query term</b> ...",
            "link": "http://www.google.com/patents/US9141672",
            "displayLink": "www.google.com",
            "snippet": "Sep 22, 2015 ... For example, a particular optionalization rule can specify that “extreme” should be optionalized, but only when in the context of “bungee jump.”.",
            "htmlSnippet": "Sep 22, 2015 <b>...</b> For example, a particular optionalization rule can specify that “extreme” should be optionalized, but only when in the <b>context</b> of “bungee jump.”.",
            "formattedUrl": "www.google.com/patents/US9141672",
            "htmlFormattedUrl": "www.google.com/patents/US9141672",
            "pagemap": {
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:13/727,968",
                        "citation_patent_number": "US:9141672",
                        "dc.description": "Methods, systems, and apparatus, including computer programs encoded on a computer storage medium, for click or skip evaluation of optionalization rules. In one aspect, a method includes accessing query log data that identifies, for an initial search query, one or more revised search queries that were identified by designating a query term of the initial search query as optional according to one or more optionalization rules, and a particular search result selected by the user. A determination is made, using the query log data, that the particular search result corresponds to the one or more revised search queries that were identified by designating the query term of the initial search query as optional according to one or more optionalization rules. In response to this determination, a click count is incremented for the one or more optionalization rules that corresponds to the particular search result.",
                        "dc.type": "patent",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:4164025",
                        "dc.title": "Click or skip evaluation of query term optionalization rule",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/a3/03/9b/158a12ea70dce3/US9141672.pdf",
                        "dc.date": "2012-12-27",
                        "dc.contributor": "Dan Popovici"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "US8041730B1 - Using geographic data to identify correlated ...",
            "htmlTitle": "US8041730B1 - Using geographic data to identify correlated ...",
            "link": "https://www.google.com/patents/US8041730",
            "displayLink": "www.google.com",
            "snippet": "A correlated geographic synonym occurs when two terms that are possible synonyms ... “Determining Query Term Synonyms within Query Context,” having a Ser.",
            "htmlSnippet": "A correlated geographic synonym occurs when two <b>terms</b> that are possible synonyms ... “Determining <b>Query Term</b> Synonyms within <b>Query Context</b>,” having a Ser.",
            "formattedUrl": "https://www.google.com/patents/US8041730",
            "htmlFormattedUrl": "https://www.google.com/patents/US8041730",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR7dPSbQnhG1TuuhKyTBxElYW3HNCs_bPil1D1scK3GovAoEDpwqn3v3AQ",
                        "width": "134",
                        "height": "120"
                    }
                ],
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:11/923,424",
                        "citation_patent_number": "US:8041730",
                        "dc.description": "One embodiment of the present invention provides a system that that uses geographic data to identify correlated geographic synonyms in search queries. A correlated geographic synonym occurs when two terms that are possible synonyms should not be considered synonyms because they are associated with related geographic context. During operation, the system receives a term and a possible synonym for the term. The system then determines whether the term and the possible synonym are both present in a geographic data set. If so, the system uses the geographic data set to determine whether the possible synonym is a correlated geographic synonym for the term.",
                        "dc.type": "patent",
                        "citation_reference": "Office Action for related case (U.S. Appl. No. 11/582,767), mailed from USPTO on Sep. 15, 2008",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:5424947",
                        "dc.title": "Using geographic data to identify correlated geographic synonyms",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/cc/81/5f/7f1823b675a3dc/US8041730.pdf",
                        "dc.date": "2007-10-24",
                        "dc.contributor": "Trystan G. Upstill"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://patentimages.storage.googleapis.com/25/a0/03/c4043c48fe11dd/US08041730-20111018-D00005.png"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "US20060224554A1 - Query revision using known highly-ranked ...",
            "htmlTitle": "US20060224554A1 - <b>Query</b> revision using known highly-ranked ...",
            "link": "http://www.google.com/patents/US20060224554",
            "displayLink": "www.google.com",
            "snippet": "An information retrieval system includes a query revision architecture providing one ... of the results is very dependent on the context of the query terms.",
            "htmlSnippet": "An information retrieval system includes a <b>query</b> revision architecture providing one ... of the results is very dependent on the <b>context</b> of the <b>query terms</b>.",
            "formattedUrl": "www.google.com/patents/US20060224554",
            "htmlFormattedUrl": "www.google.com/patents/US20060224554",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSgx6axS-JtiZpgHfNl3aS7j7uJT3V-sn1NaHvAX_qG1fhsuAKMwRI_mg",
                        "width": "123",
                        "height": "120"
                    }
                ],
                "metatags": [
                    {
                        "referrer": "origin-when-crossorigin",
                        "citation_patent_application_number": "US:11/285,814",
                        "dc.description": "An information retrieval system includes a query revision architecture providing one or more query revisers, each of which implements a query revision strategy. A query rank reviser suggests known highly-ranked queries as revisions to a first query by initially assigning a rank to all queries, and identifying a set of known highly-ranked queries (KHRQ). Queries with a strong probability of being revised to a KHRQ are identified as nearby queries (NQ). Alternative queries that are KHRQs are provided as candidate revisions for a given query. For alternative queries that are NQs, the corresponding known highly-ranked queries are provided as candidate revisions.",
                        "citation_patent_publication_number": "US:20060224554:A1",
                        "dc.type": "patent",
                        "viewport": "width=device-width, initial-scale=1",
                        "dc.relation": "US:6088692",
                        "dc.title": "Query revision using known highly-ranked queries",
                        "citation_pdf_url": "https://patentimages.storage.googleapis.com/ef/05/d7/8d684e9c1ff8d0/US20060224554A1.pdf",
                        "dc.date": "2005-11-22",
                        "dc.contributor": "David Bailey"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://patentimages.storage.googleapis.com/13/f3/4f/c4f29cddb93d93/US20060224554A1-20061005-D00003.png"
                    }
                ]
            }
        }
    ]
}